""" Constants for the integration """
PARAM_ERRORS = "errors"
PARAM_CURRENT_TEMPERATURE = "current_temperature"
PARAM_REQUIRED_TEMPERATURE = "required_temperature"
PARAM_MODE = "mode"
PARAM_ON = "power"
PARAM_SHOWERS = "showers"
PARAM_HEATING = "heating"
PARAM_CLEANSE = "antilegionella"
PARAM_ECO = "eco"
PARAM_TIMER = "remaining_time"
PARAM_CLEANSE_MIN = "antilegionella_minimum_temperature"
PARAM_CLEANSE_MAX = "antilegionella_maximum_temperature"
PARAM_CLEANSE_TEMPERATURE = "antilegionella_set_temperature"
PARAM_ONLINE_VERSION = "online_version"
PARAM_INSTALLED_VERSION = "installed_version"
PARAM_UPDATE = "update"
PARAM_TIME_PROGRAM = "time_program"
PARAM_ENERGY_USE_DAY = "energy_use_in_day"
PARAM_ENERGY_USE_WEEK = "energy_use_in_week"
PARAM_ENERGY_USE_MONTH = "energy_use_in_month"
PARAM_ENERGY_USE_YEAR = "energy_use_in_year"
PARAM_ENERGY_USE_DAY_PERIODS = "energy_use_in_day_periods"
PARAM_ENERGY_USE_WEEK_PERIODS = "energy_use_in_week_periods"
PARAM_ENERGY_USE_MONTH_PERIODS = "energy_use_in_month_periods"
PARAM_ENERGY_USE_YEAR_PERIODS = "energy_use_in_year_periods"
PARAM_REQUIRED_SHOWERS = "required_showers"
PARAM_REQUIRED_SHOWERS_MAX = "max_required_showers"
PARAM_TEMPERATURE_MODE = "temperature_mode"

PARAM_ONLINE = "online"
PARAM_CHANGING_DATA = "changing_data"

VAL_OFF = "off"
VAL_ON = "on"
VAL_MANUAL = "manual"
VAL_PROGRAM = "program"
VAL_SHOWERS = "showers"

TYPE_LYDOS = "lydos"
TYPE_LYDOS_HYBRID = "lydos_hybrid"
TYPE_VELIS = "velis"

CONF_MAX_RETRIES = "max_retries"
CONF_STORE_CONFIG_FILES = "store_config_files"
CONF_TYPE = "type"
CONF_POLLING = "polling"
CONF_LOG = "logging"
CONF_PATH = "path"
CONF_GW = "gw"

VALUE = "value"
UNITS = "units"

DOMAIN = "aquaariston"
DATA_ARISTONAQUA = DOMAIN
DEVICES = "aqua_devices"
SERVICE_SET_DATA = "aqua_set_data"
WATER_HEATERS = "aqua_water_heaters"
